class MyException extends Exception {
    private String teks;

    MyException(String s) {
        teks = "Exception generated by: " + s;
        System.out.println(teks);
    }
}

class Eksepsi {
    static void tampil(String s) throws Exception {
        System.out.println("Tampil");

        if (s.equals("amir")) {
            throw new MyException(s);
        }

        System.out.println("OK!");
    }

    public static void main(String[] args) throws Exception {
        try {
            tampil("ali");   // Tidak menyebabkan exception
            tampil("amir");  // Akan melempar exception
        } catch (MyException ex) {
            System.out.println("Tangkap: " + ex);
        }
    }
}